# Generated by Django 4.2 on 2023-07-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_car_alter_tracker_car_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="mileage",
            field=models.PositiveIntegerField(),
        ),
    ]
